log_level: "debug"
use_data_base_storage: true
postgres_url: "postgresql://postgres:password@postgres:5432/calendar?sslmode=disable"
grpc_address: "calendar:8090"
http_server:
  address: "calendar:8085"
  timeout: 30s